import React, { useState } from 'react';
import { Button } from '../ui/button';
import {
  ArrowLeft,
  FileText,
  CheckCircle,
  Circle,
  Clock,
  Sparkles,
  Download,
  RefreshCw,
  Settings,
  Eye,
  FolderOpen,
  ChevronRight,
  Zap
} from 'lucide-react';
import { WorkpaperLayout } from './WorkpaperLayout';
import { toast } from 'sonner';

interface DynamicBinderProps {
  onNavigate?: (page: string) => void;
}

interface BinderSection {
  id: string;
  category: string;
  name: string;
  status: 'complete' | 'in-progress' | 'not-started' | 'auto-generated';
  completion: number;
  autoGenerated: boolean;
  required: boolean;
  workpaperCount: number;
  lastUpdated: string;
}

export function DynamicBinderGenerator({ onNavigate }: DynamicBinderProps) {
  const [entityType, setEntityType] = useState('company');
  const [generating, setGenerating] = useState(false);

  const binderSections: BinderSection[] = [
    // Core Sections
    {
      id: 'TB',
      category: 'Core',
      name: 'Trial Balance',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '2 min ago'
    },
    {
      id: 'LS',
      category: 'Core',
      name: 'Lead Schedules',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 12,
      lastUpdated: '5 min ago'
    },
    
    // Account Workpapers
    {
      id: 'CASH',
      category: 'Assets',
      name: 'Cash at Bank',
      status: 'complete',
      completion: 100,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '10 min ago'
    },
    {
      id: 'AR',
      category: 'Assets',
      name: 'Accounts Receivable',
      status: 'in-progress',
      completion: 75,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '15 min ago'
    },
    {
      id: 'INV',
      category: 'Assets',
      name: 'Inventory',
      status: 'in-progress',
      completion: 60,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '20 min ago'
    },
    {
      id: 'FA',
      category: 'Assets',
      name: 'Fixed Assets',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '8 min ago'
    },

    // Liabilities
    {
      id: 'AP',
      category: 'Liabilities',
      name: 'Accounts Payable',
      status: 'complete',
      completion: 100,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '12 min ago'
    },
    {
      id: 'LOAN',
      category: 'Liabilities',
      name: 'Loans',
      status: 'complete',
      completion: 100,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '18 min ago'
    },

    // Income Statement
    {
      id: 'REV',
      category: 'Income Statement',
      name: 'Revenue Analysis',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '6 min ago'
    },
    {
      id: 'COGS',
      category: 'Income Statement',
      name: 'Cost of Goods Sold',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '7 min ago'
    },
    {
      id: 'WAGES',
      category: 'Income Statement',
      name: 'Wages & Salaries',
      status: 'in-progress',
      completion: 80,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '14 min ago'
    },

    // Tax Worksheets
    {
      id: 'TAX',
      category: 'Tax',
      name: 'Tax Calculation Worksheet',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '4 min ago'
    },
    {
      id: 'DTL',
      category: 'Tax',
      name: 'Deferred Tax Liability',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '5 min ago'
    },
    {
      id: 'FRANKING',
      category: 'Tax',
      name: 'Franking Account',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '6 min ago'
    },

    // Compliance
    {
      id: 'DIV7A',
      category: 'Compliance',
      name: 'Division 7A Analysis',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '9 min ago'
    },
    {
      id: 'RELATED',
      category: 'Compliance',
      name: 'Related Party Transactions',
      status: 'complete',
      completion: 100,
      autoGenerated: false,
      required: true,
      workpaperCount: 1,
      lastUpdated: '11 min ago'
    },
    {
      id: 'BAS',
      category: 'Compliance',
      name: 'BAS Reconciliation',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 4,
      lastUpdated: '13 min ago'
    },

    // Checklists
    {
      id: 'CL-RET',
      category: 'Checklists',
      name: 'Client Retention Checklist',
      status: 'complete',
      completion: 100,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '3 min ago'
    },
    {
      id: 'CL-COMP',
      category: 'Checklists',
      name: 'Company Tax Return Checklist',
      status: 'in-progress',
      completion: 85,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: '16 min ago'
    },
    {
      id: 'CL-REV',
      category: 'Checklists',
      name: 'Review Checklist',
      status: 'not-started',
      completion: 0,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: 'Not started'
    },

    // Sign-off
    {
      id: 'SIGN',
      category: 'Sign-off',
      name: 'Sign-off Summary',
      status: 'not-started',
      completion: 0,
      autoGenerated: true,
      required: true,
      workpaperCount: 1,
      lastUpdated: 'Not started'
    }
  ];

  const categories = [...new Set(binderSections.map(s => s.category))];
  
  const stats = {
    total: binderSections.length,
    complete: binderSections.filter(s => s.status === 'complete').length,
    inProgress: binderSections.filter(s => s.status === 'in-progress').length,
    autoGenerated: binderSections.filter(s => s.autoGenerated).length,
    avgCompletion: Math.round(
      binderSections.reduce((sum, s) => sum + s.completion, 0) / binderSections.length
    )
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'complete':
        return <span className="px-2 py-0.5 bg-green-100 text-green-700 text-xs font-semibold rounded flex items-center gap-1">
          <CheckCircle className="w-3 h-3" />
          Complete
        </span>;
      case 'in-progress':
        return <span className="px-2 py-0.5 bg-blue-100 text-blue-700 text-xs font-semibold rounded flex items-center gap-1">
          <Clock className="w-3 h-3" />
          In Progress
        </span>;
      case 'not-started':
        return <span className="px-2 py-0.5 bg-gray-100 text-gray-700 text-xs font-semibold rounded flex items-center gap-1">
          <Circle className="w-3 h-3" />
          Not Started
        </span>;
      case 'auto-generated':
        return <span className="px-2 py-0.5 bg-purple-100 text-purple-700 text-xs font-semibold rounded flex items-center gap-1">
          <Sparkles className="w-3 h-3" />
          Auto-Generated
        </span>;
      default:
        return null;
    }
  };

  const handleGenerateBinder = () => {
    setGenerating(true);
    toast.info('Generating workpaper binder...', {
      description: 'Building dynamic binder based on entity type and risk profile'
    });
    
    setTimeout(() => {
      setGenerating(false);
      toast.success('Binder generated', {
        description: '21 workpapers auto-generated based on trial balance activity'
      });
    }, 3000);
  };

  const handleExportBinder = () => {
    toast.success('Exporting binder', {
      description: 'Generating PDF workpaper binder...'
    });
  };

  return (
    <WorkpaperLayout currentPage="binder-generator" onNavigate={onNavigate}>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={() => onNavigate?.('dashboard')}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
            <div>
              <h1 className="text-2xl font-semibold text-gray-900 flex items-center gap-2">
                <FolderOpen className="w-6 h-6 text-green-600" />
                Dynamic Workpaper Binder
              </h1>
              <p className="text-sm text-gray-600 mt-1">Smith Family Trust • FY2024 • Company</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button 
              variant="outline" 
              size="sm" 
              onClick={handleGenerateBinder}
              disabled={generating}
            >
              {generating ? (
                <>
                  <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 mr-2" />
                  Regenerate Binder
                </>
              )}
            </Button>
            <Button variant="outline" size="sm" onClick={handleExportBinder}>
              <Download className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
            <Button className="bg-green-600 hover:bg-green-700">
              <Eye className="w-4 h-4 mr-2" />
              Preview Binder
            </Button>
          </div>
        </div>

        {/* Stats Bar */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <div className="bg-white border border-gray-300 rounded p-3">
            <div className="text-xs text-gray-600 mb-1">Total Sections</div>
            <div className="text-2xl font-bold text-gray-900">{stats.total}</div>
          </div>
          <div className="bg-white border border-gray-300 rounded p-3">
            <div className="text-xs text-gray-600 mb-1">Complete</div>
            <div className="text-2xl font-bold text-green-600">{stats.complete}</div>
          </div>
          <div className="bg-white border border-gray-300 rounded p-3">
            <div className="text-xs text-gray-600 mb-1">In Progress</div>
            <div className="text-2xl font-bold text-blue-600">{stats.inProgress}</div>
          </div>
          <div className="bg-white border border-gray-300 rounded p-3">
            <div className="text-xs text-gray-600 mb-1">Auto-Generated</div>
            <div className="text-2xl font-bold text-purple-600">{stats.autoGenerated}</div>
          </div>
          <div className="bg-white border border-gray-300 rounded p-3">
            <div className="text-xs text-gray-600 mb-1">Completion</div>
            <div className="text-2xl font-bold text-blue-600">{stats.avgCompletion}%</div>
          </div>
        </div>

        {/* Info Banner */}
        <div className="bg-green-50 border border-green-300 rounded px-4 py-3">
          <div className="flex items-start gap-3">
            <Sparkles className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold text-green-900">Dynamic Binder Generation</h3>
              <p className="text-sm text-green-800 mt-1">
                This binder was automatically generated based on: <strong>Company entity type</strong>, <strong>Trial balance activity</strong>, <strong>Risk profile (Medium)</strong>, and <strong>Prior year structure</strong>. 
                {stats.autoGenerated} of {stats.total} sections were auto-generated ({Math.round((stats.autoGenerated / stats.total) * 100)}%).
              </p>
            </div>
          </div>
        </div>

        {/* Entity Type Selector */}
        <div className="bg-white border border-gray-300 rounded p-4">
          <h3 className="font-semibold text-gray-900 mb-3">Binder Configuration</h3>
          <div className="flex items-center gap-4">
            <label className="text-sm text-gray-700">Entity Type:</label>
            <select
              value={entityType}
              onChange={(e) => setEntityType(e.target.value)}
              className="px-3 py-2 border border-gray-300 rounded text-sm focus:outline-none focus:ring-2 focus:ring-green-500"
            >
              <option value="company">Company</option>
              <option value="trust">Trust</option>
              <option value="partnership">Partnership</option>
              <option value="individual">Individual</option>
              <option value="smsf">SMSF</option>
            </select>
            <Button size="sm" variant="outline">
              <Settings className="w-4 h-4 mr-2" />
              Advanced Settings
            </Button>
          </div>
        </div>

        {/* Binder Sections Table */}
        <div className="border border-gray-300 rounded bg-white overflow-hidden">
          <div className="bg-gray-50 border-b border-gray-300 px-4 py-2">
            <h3 className="font-semibold text-gray-900">Workpaper Binder Structure</h3>
          </div>

          <table className="w-full text-sm border-collapse">
            {/* Header Row */}
            <thead>
              <tr className="bg-gray-50">
                <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-gray-700 w-8">Ref</th>
                <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-gray-700 w-40">Category</th>
                <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-gray-700">Section Name</th>
                <th className="border border-gray-300 px-3 py-2 text-center font-semibold text-gray-700 w-24">WPs</th>
                <th className="border border-gray-300 px-3 py-2 text-center font-semibold text-gray-700 w-32">Status</th>
                <th className="border border-gray-300 px-3 py-2 text-center font-semibold text-gray-700 w-28">Completion</th>
                <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-gray-700 w-32">Last Updated</th>
                <th className="border border-gray-300 px-3 py-2 text-center font-semibold text-gray-700 w-20">Auto</th>
                <th className="border border-gray-300 px-3 py-2 text-center font-semibold text-gray-700 w-24">Actions</th>
              </tr>
            </thead>

            {/* Data Rows Grouped by Category */}
            <tbody>
              {categories.map((category) => {
                const categorySections = binderSections.filter(s => s.category === category);
                return (
                  <React.Fragment key={category}>
                    {/* Category Header */}
                    <tr className="bg-gray-100">
                      <td colSpan={9} className="border border-gray-300 px-3 py-2">
                        <div className="flex items-center gap-2">
                          <ChevronRight className="w-4 h-4 text-gray-600" />
                          <span className="font-semibold text-gray-900 uppercase text-xs">
                            {category} ({categorySections.length})
                          </span>
                        </div>
                      </td>
                    </tr>

                    {/* Section Rows */}
                    {categorySections.map((section) => (
                      <tr key={section.id} className="hover:bg-gray-50">
                        <td className="border border-gray-300 px-3 py-2 text-center font-mono text-xs text-gray-600">
                          {section.id}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-gray-700 text-xs">
                          {section.category}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-gray-900">
                          {section.name}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-center font-mono text-gray-900">
                          {section.workpaperCount}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-center">
                          {getStatusBadge(section.status)}
                        </td>
                        <td className="border border-gray-300 px-3 py-2">
                          <div className="flex items-center gap-2">
                            <div className="flex-1 bg-gray-200 rounded-full h-2">
                              <div 
                                className={`h-2 rounded-full ${
                                  section.completion === 100 ? 'bg-green-600' :
                                  section.completion >= 50 ? 'bg-blue-600' : 'bg-orange-600'
                                }`}
                                style={{ width: `${section.completion}%` }}
                              />
                            </div>
                            <span className="text-xs font-mono text-gray-700 w-10 text-right">
                              {section.completion}%
                            </span>
                          </div>
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-gray-700 text-xs">
                          {section.lastUpdated}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-center">
                          {section.autoGenerated && (
                            <Sparkles className="w-4 h-4 text-purple-600 mx-auto" title="Auto-generated" />
                          )}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center">
                          <button 
                            onClick={() => {
                              toast.info(`Opening ${section.name}`, {
                                description: 'Navigating to workpaper section'
                              });
                              // Navigate to appropriate workpaper type based on section
                              if (section.id === 'DIV7A') {
                                onNavigate?.('division-7a-form');
                              } else if (section.id.startsWith('CL-')) {
                                onNavigate?.('checklist-workpaper');
                              } else if (section.id === 'LS' || section.category === 'Assets' || section.category === 'Liabilities') {
                                onNavigate?.('lead-schedule-editor');
                              } else {
                                onNavigate?.('workpaper-detail');
                              }
                            }}
                            className="px-2 py-1 text-xs bg-blue-100 text-blue-700 hover:bg-blue-200 rounded font-semibold"
                          >
                            Open →
                          </button>
                        </td>
                      </tr>
                    ))}
                  </React.Fragment>
                );
              })}
            </tbody>
          </table>
        </div>

        {/* Generation Rules */}
        <div className="bg-blue-50 border border-blue-300 rounded px-4 py-3">
          <h4 className="font-semibold text-blue-900 mb-2 flex items-center gap-2">
            <Zap className="w-5 h-5" />
            Dynamic Generation Rules
          </h4>
          <div className="text-sm text-blue-800 space-y-1">
            <p>• <strong>Lead schedules</strong> auto-generated for all TB accounts with materiality &gt; $50K</p>
            <p>• <strong>Tax worksheets</strong> included based on entity type (Company = Franking, DTL)</p>
            <p>• <strong>Division 7A analysis</strong> auto-included for companies with shareholder loans</p>
            <p>• <strong>BAS reconciliation</strong> included if GST registered</p>
            <p>• <strong>Checklists</strong> customized for entity type and compliance requirements</p>
            <p>• <strong>SMSF modules</strong> added only if entity type = SMSF</p>
          </div>
        </div>
      </div>
    </WorkpaperLayout>
  );
}