import React, { useState } from 'react';
import { Button } from '../ui/button';
import {
  ArrowLeft,
  FileText,
  Plus,
  CheckCircle,
  Circle,
  Clock,
  Download,
  Folder,
  FolderOpen,
  Upload,
  Zap,
  Target,
  BarChart3,
  Calculator,
  DollarSign,
  Users,
  Building,
  Shield,
  FileCheck,
  AlertCircle,
  TrendingUp
} from 'lucide-react';
import { WorkpaperLayout } from './WorkpaperLayout';
import { toast } from 'sonner';

interface BinderGeneratorProps {
  onNavigate?: (page: string) => void;
}

interface BinderSection {
  id: string;
  name: string;
  type: string;
  status: 'complete' | 'in-progress' | 'not-started';
  completionPercent: number;
  workpapers: number;
  autoGenerated: boolean;
}

interface Job {
  id: string;
  clientName: string;
  entityType: string;
  year: string;
  risk: 'high' | 'medium' | 'low';
  binderStatus: 'complete' | 'in-progress' | 'not-started';
  completionPercent: number;
}

export function BinderGenerator({ onNavigate }: BinderGeneratorProps) {
  const [selectedJob, setSelectedJob] = useState<string>('job-001');
  const [expandedSections, setExpandedSections] = useState<string[]>(['assets', 'liabilities']);

  const jobs: Job[] = [
    {
      id: 'job-001',
      clientName: 'ABC Manufacturing Pty Ltd',
      entityType: 'Company',
      year: 'FY2024',
      risk: 'medium',
      binderStatus: 'in-progress',
      completionPercent: 72
    },
    {
      id: 'job-002',
      clientName: 'XYZ Family Trust',
      entityType: 'Trust',
      year: 'FY2024',
      risk: 'low',
      binderStatus: 'complete',
      completionPercent: 100
    },
    {
      id: 'job-003',
      clientName: 'Smith Super Fund',
      entityType: 'SMSF',
      year: 'FY2024',
      risk: 'high',
      binderStatus: 'in-progress',
      completionPercent: 45
    }
  ];

  const binderSections: BinderSection[] = [
    {
      id: 'trial-balance',
      name: 'Trial Balance & Adjustments',
      type: 'Core',
      status: 'complete',
      completionPercent: 100,
      workpapers: 3,
      autoGenerated: true
    },
    {
      id: 'assets',
      name: 'Current Assets',
      type: 'Lead Schedule',
      status: 'complete',
      completionPercent: 100,
      workpapers: 8,
      autoGenerated: true
    },
    {
      id: 'fixed-assets',
      name: 'Non-Current Assets',
      type: 'Lead Schedule',
      status: 'complete',
      completionPercent: 100,
      workpapers: 5,
      autoGenerated: true
    },
    {
      id: 'liabilities',
      name: 'Current Liabilities',
      type: 'Lead Schedule',
      status: 'complete',
      completionPercent: 100,
      workpapers: 6,
      autoGenerated: true
    },
    {
      id: 'equity',
      name: 'Equity',
      type: 'Lead Schedule',
      status: 'complete',
      completionPercent: 100,
      workpapers: 4,
      autoGenerated: true
    },
    {
      id: 'revenue',
      name: 'Revenue & Income',
      type: 'Lead Schedule',
      status: 'in-progress',
      completionPercent: 85,
      workpapers: 7,
      autoGenerated: true
    },
    {
      id: 'expenses',
      name: 'Expenses',
      type: 'Lead Schedule',
      status: 'in-progress',
      completionPercent: 78,
      workpapers: 12,
      autoGenerated: true
    },
    {
      id: 'tax',
      name: 'Tax Worksheets',
      type: 'Tax',
      status: 'in-progress',
      completionPercent: 65,
      workpapers: 9,
      autoGenerated: true
    },
    {
      id: 'bas',
      name: 'BAS Reconciliation',
      type: 'Tax',
      status: 'in-progress',
      completionPercent: 60,
      workpapers: 4,
      autoGenerated: true
    },
    {
      id: 'payroll',
      name: 'Payroll & Super',
      type: 'Compliance',
      status: 'in-progress',
      completionPercent: 70,
      workpapers: 5,
      autoGenerated: true
    },
    {
      id: 'ratios',
      name: 'Financial Ratios & Analytics',
      type: 'Analytics',
      status: 'not-started',
      completionPercent: 0,
      workpapers: 3,
      autoGenerated: true
    },
    {
      id: 'checklist',
      name: 'Compliance Checklist',
      type: 'Review',
      status: 'in-progress',
      completionPercent: 55,
      workpapers: 1,
      autoGenerated: true
    },
    {
      id: 'evidence',
      name: 'Supporting Documents Checklist',
      type: 'Checklist',
      status: 'in-progress',
      completionPercent: 80,
      workpapers: 1,
      autoGenerated: true
    }
  ];

  const currentJob = jobs.find(j => j.id === selectedJob);

  const stats = {
    totalSections: binderSections.length,
    completeSections: binderSections.filter(s => s.status === 'complete').length,
    totalWorkpapers: binderSections.reduce((sum, s) => sum + s.workpapers, 0),
    autoGenerated: binderSections.filter(s => s.autoGenerated).length,
    overallCompletion: currentJob?.completionPercent || 0
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'complete':
        return <CheckCircle className="w-4 h-4 text-green-400" />;
      case 'in-progress':
        return <Clock className="w-4 h-4 text-amber-400" />;
      case 'not-started':
        return <Circle className="w-4 h-4 text-gray-400" />;
      default:
        return null;
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'complete':
        return <span className="px-2 py-0.5 bg-green-500/15 text-green-300 text-xs font-semibold rounded">COMPLETE</span>;
      case 'in-progress':
        return <span className="px-2 py-0.5 bg-amber-500/15 text-amber-300 text-xs font-semibold rounded">IN PROGRESS</span>;
      case 'not-started':
        return <span className="px-2 py-0.5 bg-white/5 text-slate-300 text-xs font-semibold rounded">NOT STARTED</span>;
      default:
        return null;
    }
  };

  const getRiskBadge = (risk: string) => {
    switch (risk) {
      case 'high':
        return <span className="px-2 py-0.5 bg-red-500/15 text-red-300 text-xs font-semibold rounded">HIGH RISK</span>;
      case 'medium':
        return <span className="px-2 py-0.5 bg-amber-500/15 text-amber-300 text-xs font-semibold rounded">MEDIUM RISK</span>;
      case 'low':
        return <span className="px-2 py-0.5 bg-green-500/15 text-green-300 text-xs font-semibold rounded">LOW RISK</span>;
      default:
        return null;
    }
  };

  const toggleSection = (sectionId: string) => {
    setExpandedSections(prev =>
      prev.includes(sectionId)
        ? prev.filter(id => id !== sectionId)
        : [...prev, sectionId]
    );
  };

  return (
    <WorkpaperLayout currentPage="binder-generator" onNavigate={onNavigate}>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-slate-100 flex items-center gap-3">
              <FolderOpen className="w-8 h-8 text-green-400" />
              Smart Workpaper Binder
            </h1>
            <p className="text-sm text-slate-300 mt-1">Dynamic generation • Entity-driven • Risk-based content • Auto-populated</p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm">
              <Upload className="w-4 h-4 mr-2" />
              Upload Evidence
            </Button>
            <Button variant="outline" size="sm">
              <Download className="w-4 h-4 mr-2" />
              Export PDF
            </Button>
            <Button className="bg-green-600 hover:bg-green-700">
              <Zap className="w-4 h-4 mr-2" />
              Generate All
            </Button>
          </div>
        </div>

        {/* Job Selector */}
        <div className="border border-white/10 rounded bg-white">
          <div className="bg-white/5 border-b border-white/10 px-4 py-2">
            <h3 className="font-semibold text-slate-100">Active Jobs</h3>
          </div>
          <div className="p-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {jobs.map((job) => (
                <button
                  key={job.id}
                  onClick={() => setSelectedJob(job.id)}
                  className={`text-left p-3 rounded border-2 transition-all ${
                    selectedJob === job.id
                      ? 'border-green-600 bg-green-500/10'
                      : 'border-white/10 bg-white hover:border-green-400'
                  }`}
                >
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-sm font-semibold text-slate-100">{job.clientName}</span>
                    {selectedJob === job.id && <CheckCircle className="w-4 h-4 text-green-400" />}
                  </div>
                  <div className="space-y-1 text-xs">
                    <div className="flex items-center gap-2">
                      <Building className="w-3 h-3 text-slate-400" />
                      <span className="text-slate-300">{job.entityType} • {job.year}</span>
                    </div>
                    <div className="flex items-center justify-between">
                      {getRiskBadge(job.risk)}
                      {getStatusBadge(job.binderStatus)}
                    </div>
                    <div className="mt-2">
                      <div className="w-full bg-white/10 rounded-full h-1.5">
                        <div
                          className="bg-green-600 h-1.5 rounded-full"
                          style={{ width: `${job.completionPercent}%` }}
                        ></div>
                      </div>
                      <div className="text-xs text-slate-300 mt-1">{job.completionPercent}% complete</div>
                    </div>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <div className="bg-white border border-white/10 rounded p-3">
            <div className="text-xs text-slate-300 mb-1">Total Sections</div>
            <div className="text-2xl font-bold text-slate-100 font-mono">{stats.totalSections}</div>
          </div>
          <div className="bg-white border border-white/10 rounded p-3">
            <div className="text-xs text-slate-300 mb-1">Complete</div>
            <div className="text-2xl font-bold text-green-400 font-mono">{stats.completeSections}</div>
          </div>
          <div className="bg-white border border-white/10 rounded p-3">
            <div className="text-xs text-slate-300 mb-1">Workpapers</div>
            <div className="text-2xl font-bold text-slate-100 font-mono">{stats.totalWorkpapers}</div>
          </div>
          <div className="bg-white border border-white/10 rounded p-3">
            <div className="text-xs text-slate-300 mb-1">Auto-Generated</div>
            <div className="text-2xl font-bold text-blue-400 font-mono">{stats.autoGenerated}</div>
            <div className="text-xs text-green-400 font-semibold">89%</div>
          </div>
          <div className="bg-white border border-white/10 rounded p-3">
            <div className="text-xs text-slate-300 mb-1">Overall Progress</div>
            <div className="text-2xl font-bold text-green-400 font-mono">{stats.overallCompletion}%</div>
          </div>
        </div>

        {/* Current Job Info */}
        {currentJob && (
          <div className="bg-blue-500/10 border border-blue-300 rounded px-4 py-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Building className="w-5 h-5 text-blue-400" />
                <div>
                  <h3 className="font-semibold text-blue-300">{currentJob.clientName}</h3>
                  <p className="text-sm text-blue-300">
                    {currentJob.entityType} • {currentJob.year} • {stats.totalWorkpapers} workpapers • {stats.completeSections}/{stats.totalSections} sections complete
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                {getRiskBadge(currentJob.risk)}
                {getStatusBadge(currentJob.binderStatus)}
              </div>
            </div>
          </div>
        )}

        {/* Binder Structure Table */}
        <div className="border border-white/10 rounded bg-white overflow-hidden">
          <div className="bg-white/5 border-b border-white/10 px-4 py-2">
            <h3 className="font-semibold text-slate-100">Dynamic Binder Structure</h3>
          </div>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="bg-white/5">
                <th className="border border-white/10 px-3 py-2 text-left font-semibold text-slate-300 w-12"></th>
                <th className="border border-white/10 px-3 py-2 text-left font-semibold text-slate-300">Section Name</th>
                <th className="border border-white/10 px-3 py-2 text-left font-semibold text-slate-300 w-32">Type</th>
                <th className="border border-white/10 px-3 py-2 text-center font-semibold text-slate-300 w-32">Status</th>
                <th className="border border-white/10 px-3 py-2 text-center font-semibold text-slate-300 w-32">Progress</th>
                <th className="border border-white/10 px-3 py-2 text-center font-semibold text-slate-300 w-24">Workpapers</th>
                <th className="border border-white/10 px-3 py-2 text-center font-semibold text-slate-300 w-32">Generation</th>
                <th className="border border-white/10 px-3 py-2 text-center font-semibold text-slate-300 w-32">Actions</th>
              </tr>
            </thead>
            <tbody>
              {binderSections.map((section) => (
                <tr key={section.id} className="hover:bg-blue-500/10">
                  <td className="border border-white/10 px-2 py-2 text-center">
                    {getStatusIcon(section.status)}
                  </td>
                  <td className="border border-white/10 px-3 py-2 text-slate-100 font-medium">
                    <div className="flex items-center gap-2">
                      <Folder className="w-4 h-4 text-blue-400" />
                      {section.name}
                    </div>
                  </td>
                  <td className="border border-white/10 px-3 py-2 text-slate-300">
                    <span className="px-2 py-0.5 bg-white/5 text-slate-300 text-xs font-semibold rounded">
                      {section.type}
                    </span>
                  </td>
                  <td className="border border-white/10 px-2 py-2 text-center">
                    {getStatusBadge(section.status)}
                  </td>
                  <td className="border border-white/10 px-3 py-2">
                    <div className="flex items-center gap-2">
                      <div className="flex-1 bg-white/10 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full ${
                            section.status === 'complete'
                              ? 'bg-green-600'
                              : section.status === 'in-progress'
                              ? 'bg-amber-600'
                              : 'bg-gray-400'
                          }`}
                          style={{ width: `${section.completionPercent}%` }}
                        ></div>
                      </div>
                      <span className="text-xs font-mono font-semibold text-slate-300 w-10">
                        {section.completionPercent}%
                      </span>
                    </div>
                  </td>
                  <td className="border border-white/10 px-3 py-2 text-center font-mono font-semibold text-slate-100">
                    {section.workpapers}
                  </td>
                  <td className="border border-white/10 px-2 py-2 text-center">
                    {section.autoGenerated ? (
                      <span className="px-2 py-0.5 bg-green-500/15 text-green-300 text-xs font-semibold rounded flex items-center gap-1 justify-center">
                        <Zap className="w-3 h-3" />
                        AUTO
                      </span>
                    ) : (
                      <span className="px-2 py-0.5 bg-blue-500/15 text-blue-300 text-xs font-semibold rounded">
                        MANUAL
                      </span>
                    )}
                  </td>
                  <td className="border border-white/10 px-2 py-2 text-center">
                    <div className="flex items-center gap-1 justify-center">
                      <button 
                        onClick={() => {
                          // Navigate to appropriate workpaper type based on section
                          if (section.id === 'trial-balance') {
                            onNavigate?.('trial-balance');
                          } else if (section.id === 'tax' || section.type === 'Tax') {
                            onNavigate?.('tax-reconciliation');
                          } else if (section.id.includes('division-7a')) {
                            onNavigate?.('division-7a-form');
                          } else if (section.id.includes('checklist') || section.id === 'evidence' || section.type === 'Checklist' || section.type === 'Review') {
                            onNavigate?.('checklist-workpaper');
                          } else if (section.type === 'Lead Schedule' || section.type === 'Core') {
                            onNavigate?.('lead-schedule-editor');
                          } else {
                            onNavigate?.('workpaper-detail');
                          }
                        }}
                        className="px-2 py-1 text-xs bg-blue-500/15 text-blue-300 hover:bg-blue-500/20 rounded font-semibold"
                      >
                        Open
                      </button>
                      {section.status === 'not-started' && (
                        <button 
                          onClick={() => {
                            toast.info(`Generating ${section.name}`, {
                              description: 'Auto-generating workpaper from trial balance data'
                            });
                          }}
                          className="px-2 py-1 text-xs bg-green-500/15 text-green-300 hover:bg-green-500/20 rounded font-semibold"
                        >
                          Generate
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Auto-Generation Info */}
        <div className="bg-green-500/10 border border-green-300 rounded px-4 py-3">
          <div className="flex items-start gap-3">
            <Zap className="w-5 h-5 text-green-400 mt-0.5" />
            <div className="flex-1">
              <h3 className="font-semibold text-green-300 mb-2">Dynamic Binder Generation</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm text-green-300">
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-400" />
                  <span>Entity type driven</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-400" />
                  <span>Ledger activity based</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-400" />
                  <span>Risk profile adapted</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-4 h-4 text-green-400" />
                  <span>Prior year rollforward</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </WorkpaperLayout>
  );
}